/** Private blob storage. Keys are generated by the server, never derived from client input. */
export interface FileStorage {
  put(key: string, data: Buffer): Promise<void>;
  /** `undefined` when the key does not exist. */
  get(key: string): Promise<Buffer | undefined>;
  /** Idempotent. */
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}
