import { AppError, type ErrorKind } from '../../../00-shared-kernel/public';

export const SessionErrorCodes = {
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  SESSION_CONCURRENT_MODIFICATION: 'SESSION_CONCURRENT_MODIFICATION',
} as const;
export type SessionErrorCode = (typeof SessionErrorCodes)[keyof typeof SessionErrorCodes];

const KIND: Record<SessionErrorCode, ErrorKind> = {
  AUTHENTICATION_REQUIRED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'UNAUTHENTICATED',
  ACCOUNT_INACTIVE: 'FORBIDDEN',
  ACCESS_TOKEN_INVALID: 'UNAUTHENTICATED',
  ACCESS_TOKEN_EXPIRED: 'UNAUTHENTICATED',
  SESSION_REVOKED: 'UNAUTHENTICATED',
  REFRESH_TOKEN_INVALID: 'UNAUTHENTICATED',
  REFRESH_TOKEN_EXPIRED: 'UNAUTHENTICATED',
  REFRESH_TOKEN_REUSED: 'UNAUTHENTICATED',
  SESSION_CONCURRENT_MODIFICATION: 'CONFLICT',
};

export function sessionError(code: SessionErrorCode): AppError {
  return new AppError(code, KIND[code]);
}
